///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace StartAtlas
{
    public partial class Recording1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void StartApplication()
        {
        	string InstantiatorExe = @"C:\Windows\System32\notepad.exe";
        	
           // Report.Info("User", $"ATLAS Instantiaor not running. Starting {InstantiatorExe} ...");
    		if(System.IO.File.Exists(InstantiatorExe))
			{
    			Host.Local.RunApplication(InstantiatorExe, "", "", false);
    			Delay.Seconds(10);
    			try
    			{
    				repo.TeradyneAtlasInstantiator.SelfInfo.WaitForExists(10000);
    				//repo.TitanStartStop.SelfInfo.WaitForExists(4000);	
    				repo.TeradyneAtlasInstantiator.Self.Activate();
	        		Report.Info("User","Activated Atlas Instantiaor Window.");
	        	}
    			catch
    			{
    				Report.Warn("User","Atlas Instantiaor application window not found.");
    			}
    		}
        	else
        		Report.Warn("Atlas Instantiaor executable not found");
        }

    }
}
