///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace StartAtlas
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the StartAtlasRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("6939d141-4a5f-4394-8886-9514f3fadb82")]
    public partial class StartAtlasRepository : RepoGenBaseFolder
    {
        static StartAtlasRepository instance = new StartAtlasRepository();
        StartAtlasRepositoryFolders.TeradyneAtlasInstantiatorAppFolder _teradyneatlasinstantiator;

        /// <summary>
        /// Gets the singleton class instance representing the StartAtlasRepository element repository.
        /// </summary>
        [RepositoryFolder("6939d141-4a5f-4394-8886-9514f3fadb82")]
        public static StartAtlasRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public StartAtlasRepository() 
            : base("StartAtlasRepository", "/", null, 0, false, "6939d141-4a5f-4394-8886-9514f3fadb82", ".\\RepositoryImages\\StartAtlasRepository6939d141.rximgres")
        {
            _teradyneatlasinstantiator = new StartAtlasRepositoryFolders.TeradyneAtlasInstantiatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6939d141-4a5f-4394-8886-9514f3fadb82")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The TeradyneAtlasInstantiator folder.
        /// </summary>
        [RepositoryFolder("34ead688-f321-4296-95d6-819ffcff1f67")]
        public virtual StartAtlasRepositoryFolders.TeradyneAtlasInstantiatorAppFolder TeradyneAtlasInstantiator
        {
            get { return _teradyneatlasinstantiator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class StartAtlasRepositoryFolders
    {
        /// <summary>
        /// The TeradyneAtlasInstantiatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("34ead688-f321-4296-95d6-819ffcff1f67")]
        public partial class TeradyneAtlasInstantiatorAppFolder : RepoGenBaseFolder
        {
            StartAtlasRepositoryFolders.MessageListBoxFolder _messagelistbox;
            RepoItemInfo _somelistInfo;
            RepoItemInfo _btnstartstopInfo;
            RepoItemInfo _atlasinstantiatorstatusInfo;
            RepoItemInfo _instantiatormessageboxInfo;
            RepoItemInfo _somelistitemInfo;
            RepoItemInfo _btnstartatlasservicesInfo;
            RepoItemInfo _stopservicesInfo;
            RepoItemInfo _startservicesInfo;
            RepoItemInfo _startservices1Info;

            /// <summary>
            /// Creates a new TeradyneAtlasInstantiator  folder.
            /// </summary>
            public TeradyneAtlasInstantiatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TeradyneAtlasInstantiator", "/form[@windowtext='Teradyne Atlas Instantiator']", parentFolder, 30000, null, true, "34ead688-f321-4296-95d6-819ffcff1f67", "")
            {
                _messagelistbox = new StartAtlasRepositoryFolders.MessageListBoxFolder(this);
                _somelistInfo = new RepoItemInfo(this, "SomeList", "list[1]", "", 30000, null, "bda6ce3f-fd6b-4897-b58c-6c01a55016d8");
                _btnstartstopInfo = new RepoItemInfo(this, "btnStartStop", "element//button[@automationid='StartStopButton']", "", 30000, null, "2d945108-d1d7-4f9a-8736-be4288f6811d");
                _atlasinstantiatorstatusInfo = new RepoItemInfo(this, "AtlasInstantiatorStatus", "element//text[@automationid='Instantiator_StatusField']", "", 30000, null, "37795265-d30f-4255-b3ce-ea9bad0386eb");
                _instantiatormessageboxInfo = new RepoItemInfo(this, "InstantiatorMessageBox", "element//list[@automationid='Instantiator_MessageListBox']", "", 30000, null, "95ced37a-0b73-4cc1-ac2f-5274ff63bbe7");
                _somelistitemInfo = new RepoItemInfo(this, "SomeListItem", ".//element//list[@automationid='MessageListBox']//element[@automationid='Border']//listitem[@index='0']", "", 30000, null, "960ca4fa-dd64-45d6-8fab-d0d619ad75a6");
                _btnstartatlasservicesInfo = new RepoItemInfo(this, "BtnStartAtlasServices", ".//button[@text='Start Atlas Services']", "", 30000, null, "9d68d37f-f148-45a2-908d-b18dcdabda69");
                _stopservicesInfo = new RepoItemInfo(this, "StopServices", ".//button[@text='Stop Services']", "", 50000, null, "dce38917-f1c2-455a-84d6-089fc7f8d429");
                _startservicesInfo = new RepoItemInfo(this, "StartServices", "element/?/?/button[@text='Start Services']", "", 30000, null, "45ac2a08-c993-42ce-bf09-2d73409ea17e");
                _startservices1Info = new RepoItemInfo(this, "STARTSERVICES1", ".//button[@text='Start Services']/?/?/container[@automationid='PART_ContentPresenter']/?/?/container[@automationid='PART_ContentPresenter']/text[@caption='START SERVICES']", "", 30000, null, "f548c48b-7827-4c90-b3db-98b92e795838");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("34ead688-f321-4296-95d6-819ffcff1f67")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("34ead688-f321-4296-95d6-819ffcff1f67")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeList item.
            /// </summary>
            [RepositoryItem("bda6ce3f-fd6b-4897-b58c-6c01a55016d8")]
            public virtual Ranorex.List SomeList
            {
                get
                {
                    return _somelistInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The SomeList item info.
            /// </summary>
            [RepositoryItemInfo("bda6ce3f-fd6b-4897-b58c-6c01a55016d8")]
            public virtual RepoItemInfo SomeListInfo
            {
                get
                {
                    return _somelistInfo;
                }
            }

            /// <summary>
            /// The btnStartStop item.
            /// </summary>
            [RepositoryItem("2d945108-d1d7-4f9a-8736-be4288f6811d")]
            public virtual Ranorex.Button btnStartStop
            {
                get
                {
                    return _btnstartstopInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnStartStop item info.
            /// </summary>
            [RepositoryItemInfo("2d945108-d1d7-4f9a-8736-be4288f6811d")]
            public virtual RepoItemInfo btnStartStopInfo
            {
                get
                {
                    return _btnstartstopInfo;
                }
            }

            /// <summary>
            /// The AtlasInstantiatorStatus item.
            /// </summary>
            [RepositoryItem("37795265-d30f-4255-b3ce-ea9bad0386eb")]
            public virtual Ranorex.Text AtlasInstantiatorStatus
            {
                get
                {
                    return _atlasinstantiatorstatusInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AtlasInstantiatorStatus item info.
            /// </summary>
            [RepositoryItemInfo("37795265-d30f-4255-b3ce-ea9bad0386eb")]
            public virtual RepoItemInfo AtlasInstantiatorStatusInfo
            {
                get
                {
                    return _atlasinstantiatorstatusInfo;
                }
            }

            /// <summary>
            /// The InstantiatorMessageBox item.
            /// </summary>
            [RepositoryItem("95ced37a-0b73-4cc1-ac2f-5274ff63bbe7")]
            public virtual Ranorex.List InstantiatorMessageBox
            {
                get
                {
                    return _instantiatormessageboxInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The InstantiatorMessageBox item info.
            /// </summary>
            [RepositoryItemInfo("95ced37a-0b73-4cc1-ac2f-5274ff63bbe7")]
            public virtual RepoItemInfo InstantiatorMessageBoxInfo
            {
                get
                {
                    return _instantiatormessageboxInfo;
                }
            }

            /// <summary>
            /// The SomeListItem item.
            /// </summary>
            [RepositoryItem("960ca4fa-dd64-45d6-8fab-d0d619ad75a6")]
            public virtual Ranorex.ListItem SomeListItem
            {
                get
                {
                    return _somelistitemInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SomeListItem item info.
            /// </summary>
            [RepositoryItemInfo("960ca4fa-dd64-45d6-8fab-d0d619ad75a6")]
            public virtual RepoItemInfo SomeListItemInfo
            {
                get
                {
                    return _somelistitemInfo;
                }
            }

            /// <summary>
            /// The BtnStartAtlasServices item.
            /// </summary>
            [RepositoryItem("9d68d37f-f148-45a2-908d-b18dcdabda69")]
            public virtual Ranorex.Button BtnStartAtlasServices
            {
                get
                {
                    return _btnstartatlasservicesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnStartAtlasServices item info.
            /// </summary>
            [RepositoryItemInfo("9d68d37f-f148-45a2-908d-b18dcdabda69")]
            public virtual RepoItemInfo BtnStartAtlasServicesInfo
            {
                get
                {
                    return _btnstartatlasservicesInfo;
                }
            }

            /// <summary>
            /// The StopServices item.
            /// </summary>
            [RepositoryItem("dce38917-f1c2-455a-84d6-089fc7f8d429")]
            public virtual Ranorex.Button StopServices
            {
                get
                {
                    return _stopservicesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The StopServices item info.
            /// </summary>
            [RepositoryItemInfo("dce38917-f1c2-455a-84d6-089fc7f8d429")]
            public virtual RepoItemInfo StopServicesInfo
            {
                get
                {
                    return _stopservicesInfo;
                }
            }

            /// <summary>
            /// The StartServices item.
            /// </summary>
            [RepositoryItem("45ac2a08-c993-42ce-bf09-2d73409ea17e")]
            public virtual Ranorex.Button StartServices
            {
                get
                {
                    return _startservicesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The StartServices item info.
            /// </summary>
            [RepositoryItemInfo("45ac2a08-c993-42ce-bf09-2d73409ea17e")]
            public virtual RepoItemInfo StartServicesInfo
            {
                get
                {
                    return _startservicesInfo;
                }
            }

            /// <summary>
            /// The STARTSERVICES1 item.
            /// </summary>
            [RepositoryItem("f548c48b-7827-4c90-b3db-98b92e795838")]
            public virtual Ranorex.Text STARTSERVICES1
            {
                get
                {
                    return _startservices1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The STARTSERVICES1 item info.
            /// </summary>
            [RepositoryItemInfo("f548c48b-7827-4c90-b3db-98b92e795838")]
            public virtual RepoItemInfo STARTSERVICES1Info
            {
                get
                {
                    return _startservices1Info;
                }
            }

            /// <summary>
            /// The MessageListBox folder.
            /// </summary>
            [RepositoryFolder("fd8816cf-1a4b-47bb-9b5e-8d6d85a8e476")]
            public virtual StartAtlasRepositoryFolders.MessageListBoxFolder MessageListBox
            {
                get { return _messagelistbox; }
            }
        }

        /// <summary>
        /// The MessageListBoxFolder folder.
        /// </summary>
        [RepositoryFolder("fd8816cf-1a4b-47bb-9b5e-8d6d85a8e476")]
        public partial class MessageListBoxFolder : RepoGenBaseFolder
        {
            RepoItemInfo _thetitanhostpcinstantiatorhasbeeniInfo;
            RepoItemInfo _infoInfo;
            RepoItemInfo _thetitanhostpcinstantiatorhasbeeni1Info;

            /// <summary>
            /// Creates a new MessageListBox  folder.
            /// </summary>
            public MessageListBoxFolder(RepoGenBaseFolder parentFolder) :
                    base("MessageListBox", "element/?/?/list[@automationid='MessageListBox']", parentFolder, 30000, null, false, "fd8816cf-1a4b-47bb-9b5e-8d6d85a8e476", "")
            {
                _thetitanhostpcinstantiatorhasbeeniInfo = new RepoItemInfo(this, "TheTitanHostPCInstantiatorHasBeenI", ".//listitem[@index='0']/container[@automationid='RootGrid']//container[@automationid='ContentPresenter']//text[@caption~'.*']", "", 30000, null, "5410c154-5280-43c9-aad2-71098fcfd662");
                _infoInfo = new RepoItemInfo(this, "Info", "element[@automationid='Border']//listitem[@index='0']/container[@automationid='RootGrid']/?/?/container[@automationid='ContentPresenter']/?/?/text[@caption='Info']", "", 30000, null, "2b24de5a-586a-42b9-ba82-46e4ef616ab6");
                _thetitanhostpcinstantiatorhasbeeni1Info = new RepoItemInfo(this, "TheTitanHostPCInstantiatorHasBeenI1", "element[@automationid='Border']//listitem[@index='0']/container[@automationid='RootGrid']/?/?/container[@automationid='ContentPresenter']/?/?/text[@caption>'The Titan HostPC Instantiator']", "", 30000, null, "d9c94897-dca2-43a4-a098-7e5577b83919");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fd8816cf-1a4b-47bb-9b5e-8d6d85a8e476")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fd8816cf-1a4b-47bb-9b5e-8d6d85a8e476")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TheTitanHostPCInstantiatorHasBeenI item.
            /// </summary>
            [RepositoryItem("5410c154-5280-43c9-aad2-71098fcfd662")]
            public virtual Ranorex.Text TheTitanHostPCInstantiatorHasBeenI
            {
                get
                {
                    return _thetitanhostpcinstantiatorhasbeeniInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TheTitanHostPCInstantiatorHasBeenI item info.
            /// </summary>
            [RepositoryItemInfo("5410c154-5280-43c9-aad2-71098fcfd662")]
            public virtual RepoItemInfo TheTitanHostPCInstantiatorHasBeenIInfo
            {
                get
                {
                    return _thetitanhostpcinstantiatorhasbeeniInfo;
                }
            }

            /// <summary>
            /// The Info item.
            /// </summary>
            [RepositoryItem("2b24de5a-586a-42b9-ba82-46e4ef616ab6")]
            public virtual Ranorex.Text Info
            {
                get
                {
                    return _infoInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Info item info.
            /// </summary>
            [RepositoryItemInfo("2b24de5a-586a-42b9-ba82-46e4ef616ab6")]
            public virtual RepoItemInfo InfoInfo
            {
                get
                {
                    return _infoInfo;
                }
            }

            /// <summary>
            /// The TheTitanHostPCInstantiatorHasBeenI1 item.
            /// </summary>
            [RepositoryItem("d9c94897-dca2-43a4-a098-7e5577b83919")]
            public virtual Ranorex.Text TheTitanHostPCInstantiatorHasBeenI1
            {
                get
                {
                    return _thetitanhostpcinstantiatorhasbeeni1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TheTitanHostPCInstantiatorHasBeenI1 item info.
            /// </summary>
            [RepositoryItemInfo("d9c94897-dca2-43a4-a098-7e5577b83919")]
            public virtual RepoItemInfo TheTitanHostPCInstantiatorHasBeenI1Info
            {
                get
                {
                    return _thetitanhostpcinstantiatorhasbeeni1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
